name: rutas_microbuses
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  shared_preferences: ^2.0.15
  fancy_dialog: ^1.0.4
  flutter_typeahead: ^4.0.0
  flutter_map: ^0.14.0
  #image_picker: ^0.8.5+3
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
     - assets/images/