// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqRMMpkX6s6c7YS0xLoe6-JLRzqG3A7H4',
    appId: '1:261909526275:web:94cf6947173aeada421b36',
    messagingSenderId: '261909526275',
    projectId: 'ubicaciones-5704d',
    authDomain: 'ubicaciones-5704d.firebaseapp.com',
    storageBucket: 'ubicaciones-5704d.appspot.com',
    measurementId: 'G-RFQQEL4TD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEWrnW7R1HScUvICJy18irMd1NFUtiZ-U',
    appId: '1:261909526275:android:12d2fdb954083c64421b36',
    messagingSenderId: '261909526275',
    projectId: 'ubicaciones-5704d',
    storageBucket: 'ubicaciones-5704d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpiV30ByaDtWTvz5bCa6nHiN0dV0QjclY',
    appId: '1:261909526275:ios:4e10269f50ba0dbe421b36',
    messagingSenderId: '261909526275',
    projectId: 'ubicaciones-5704d',
    storageBucket: 'ubicaciones-5704d.appspot.com',
    iosClientId: '261909526275-80k2kc1feiia1meipla692irqq3fca2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.rutasMicrobuses',
  );
}
